apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: cpuload-test-v2
  namespace: default
spec:
  destination:
    name: cpuload
  match:
    request:
      headers:
        cookie:
          regex: ^(.*?;)?(userType=p)(;.*)?$
  precedence: 2
  route:
    - labels:
        version: v2
