apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: cpuload-default
  namespace: default
spec:
  destination:
    name: cpuload
  precedence: 1
  route:
    - labels:
        version: v1
