# Use the official maven/Java 8 image to create a build artifact.
# https://hub.docker.com/_/maven
FROM maven:3.5-jdk-8-alpine

# Copy local code to the container image.
WORKDIR /app
COPY pom.xml .
COPY src ./src

# install local dependency
COPY lib ./lib
RUN cd lib && ./install.sh

# Build a release artifact. - only mvn package downloads complete libs
RUN mvn package -DskipTests



